const previewUiText = {
  ru: {
    meta: {
      pageTitle: {
        dashboard: "Превью мира",
        characters: "Персонажи | Превью мира",
        places: "Места | Превью мира",
        search: "Поиск | Превью мира",
      },
    },
    shell: {
      brandEyebrow: "Phase 1 preview",
      brandTitle: "World Building App",
      brandNote: "Временный интерфейс для GitHub Pages",
      nav: {
        dashboard: "Панель",
        characters: "Персонажи",
        places: "Места",
        search: "Поиск",
      },
      previewModeTitle: "Режим предпросмотра",
      previewModeDescription: "Статический клиентский слой для проверки UX без живого Next.js и PostgreSQL.",
    },
    dashboard: {
      eyebrow: "Активный MVP-срез",
      title: "Панель текущего рабочего объёма",
      description: "Одна временная Pages-поверхность для проверки структуры, карточек, форм, тегов, связей и поиска.",
      previewBadges: ["Только preview", "Characters + Places", "Теги, связи и поиск"],
      recentTitle: "Недавние изменения в макете",
      openSearch: "Открыть поиск",
      progressTitle: "Что можно проверить сейчас",
      focusTitle: "Текущий фокус",
      focusBadge: "MVP",
      focusDescription: "Preview показывает только активный Phase 1 slice без Story, Map и других отложенных разделов.",
      reviewCharactersFlow: "Проверить поток персонажей",
      reviewPlacesFlow: "Проверить поток мест",
      coverageTitle: "Покрытие временного слоя",
      coverageBadge: "Mock only",
      coverageDescription: "Создание, редактирование, удаление, теги, простые Character↔Place связи и глобальный поиск работают только на клиентских мок-данных.",
      checklist: [
        "Dashboard отражает только реально активные MVP-сущности.",
        "Characters поддерживают список, карточку, форму, теги и связи.",
        "Places повторяют тот же базовый рабочий поток.",
        "Поиск видит имена, slug и краткие описания.",
        "Навигация не уводит в неактивные разделы.",
      ],
      capabilities: [
        "Dashboard с показателями и последними обновлениями",
        "Characters: mock list/detail/create/edit/delete",
        "Places: mock list/detail/create/edit/delete",
        "Tags: attach/remove",
        "Links: Character ↔ Place add/remove",
        "Search: results across active entities",
      ],
      stats: {
        characters: { eyebrow: "Сущности", title: "Персонажи", suffix: "записей в превью" },
        places: { eyebrow: "Сущности", title: "Места", suffix: "записей в превью" },
        tags: { eyebrow: "Связность", title: "Теги", suffix: "доступно для привязки" },
        links: { eyebrow: "Связность", title: "Character ↔ Place", suffix: "активных связей" },
      },
    },
    common: {
      noSelection: "Нет выбора",
      selectFromList: "Выберите запись из списка слева.",
      noMatches: "Ничего не найдено в текущем preview-состоянии.",
      noSummary: "Краткое описание не заполнено",
      noValue: "—",
      selectedPrefix: "Выбрано:",
      requiredSuffix: "обязательно.",
      itemsSuffix: "элементов",
      quickFilter: "Быстрый фильтр",
      tagsTitle: "Теги",
      linksTitle: "Связанные сущности",
      attachTag: "Добавить тег",
      removeTag: "Убрать",
      addLink: "Создать связь",
      removeLink: "Удалить связь",
      linkLabel: "Подпись связи",
      linkPlaceholder: "Например: живёт в",
      savedState: "Сохранено в preview-состоянии.",
      selectRecordFirst: "Сначала выберите запись.",
      tagAlreadyAttached: "Этот тег уже прикреплён.",
      linkAlreadyExists: "Такая связь уже есть.",
      searchOpenEntity: "Открыть запись",
      searchNoQuery: "Введите запрос, чтобы посмотреть результаты.",
      searchNoResults: "По этому запросу ничего не найдено.",
      searchResultsPrefix: "Результаты по запросу:",
      deleteConfirm: "Удалить запись из preview?",
      localeLabel: "Язык",
    },
    characters: {
      eyebrow: "MVP entity",
      title: "Персонажи",
      description: "Временный рабочий слой для списка, карточки, формы, тегов и связей персонажей.",
      newButton: "Новый персонаж",
      editButton: "Редактировать выбранное",
      recordsTitle: "Список",
      detailTitle: "Карточка персонажа",
      deleteButton: "Удалить персонажа",
      form: {
        createTitle: "Создать персонажа",
        editTitle: "Редактировать персонажа",
        createMode: "Режим: создание",
        editMode: "Режим: редактирование",
        name: "Имя",
        slug: "Slug (необязательно)",
        summary: "Краткое описание",
        pronouns: "Местоимения",
        epithet: "Эпитет",
        status: "Статус",
        canon: "Канон",
        save: "Сохранить персонажа",
        reset: "Сбросить форму",
        searchPlaceholder: "Поиск по имени, slug или описанию",
        statusOptions: { draft: "Черновик", active: "Активно", archived: "Архив" },
        canonOptions: {
          canonical: "Канон",
          alternate: "Альтернатива",
          uncertain: "Неопределённо",
          noncanonical: "Неканон",
        },
      },
      detailLabels: {
        name: "Имя",
        slug: "Slug",
        summary: "Краткое описание",
        profile: "Профиль",
        state: "Состояние",
        pronouns: "Местоимения",
        epithet: "Эпитет",
      },
      links: {
        targetLabel: "Связать с местом",
      },
      messages: {
        createDraft: "Подготовка новой карточки персонажа.",
        selectBeforeEdit: "Сначала выберите персонажа для редактирования.",
        resetToCreate: "Форма сброшена. Можно создавать новую запись.",
        nothingSelectedToDelete: "Удалять пока нечего.",
        created: "Персонаж создан в preview.",
        updated: "Персонаж обновлён в preview.",
        removed: "Персонаж удалён из preview.",
        selectBeforeSave: "Сначала выберите запись для сохранения правок.",
      },
    },
    places: {
      eyebrow: "MVP entity",
      title: "Места",
      description: "Временный рабочий слой для списка, карточки, формы, тегов и связей мест.",
      newButton: "Новое место",
      editButton: "Редактировать выбранное",
      recordsTitle: "Список",
      detailTitle: "Карточка места",
      deleteButton: "Удалить место",
      form: {
        createTitle: "Создать место",
        editTitle: "Редактировать место",
        createMode: "Режим: создание",
        editMode: "Режим: редактирование",
        name: "Название",
        slug: "Slug (необязательно)",
        summary: "Краткое описание",
        placeKind: "Тип места",
        locationText: "Локация / заметка",
        status: "Статус",
        canon: "Канон",
        save: "Сохранить место",
        reset: "Сбросить форму",
        searchPlaceholder: "Поиск по имени, slug или описанию",
        statusOptions: { draft: "Черновик", active: "Активно", archived: "Архив" },
        canonOptions: {
          canonical: "Канон",
          alternate: "Альтернатива",
          uncertain: "Неопределённо",
          noncanonical: "Неканон",
        },
      },
      detailLabels: {
        name: "Название",
        slug: "Slug",
        summary: "Краткое описание",
        profile: "Профиль локации",
        state: "Состояние",
        placeKind: "Тип",
        locationText: "Расположение",
      },
      links: {
        targetLabel: "Связать с персонажем",
      },
      messages: {
        createDraft: "Подготовка новой карточки места.",
        selectBeforeEdit: "Сначала выберите место для редактирования.",
        resetToCreate: "Форма сброшена. Можно создавать новую запись.",
        nothingSelectedToDelete: "Удалять пока нечего.",
        created: "Место создано в preview.",
        updated: "Место обновлено в preview.",
        removed: "Место удалено из preview.",
        selectBeforeSave: "Сначала выберите запись для сохранения правок.",
      },
    },
    tags: {
      names: {
        capital: "Столица",
        faction: "Фракция",
        witness: "Свидетель",
        travel: "Путешествие",
        archive: "Архив",
        frontier: "Пограничье",
      },
    },
    search: {
      eyebrow: "Global search",
      title: "Поиск по активному MVP-срезу",
      description: "Простой клиентский поиск только по Characters и Places, чтобы проверить удобство общей точки входа.",
      quickLabel: "Быстрый поиск",
      placeholder: "Введите имя, slug или краткое описание",
      submit: "Искать",
      resultsTitle: "Результаты",
      coverageTitle: "Что ищется сейчас",
      coverage: [
        "Characters: name, slug, summary, epithet",
        "Places: name, slug, summary, place kind, location text",
        "Только активный MVP-срез без Story, Map и других сущностей",
      ],
    },
    entityKinds: {
      character: "Персонаж",
      place: "Место",
    },
  },
  en: {
    meta: {
      pageTitle: {
        dashboard: "World Preview",
        characters: "Characters | World Preview",
        places: "Places | World Preview",
        search: "Search | World Preview",
      },
    },
    shell: {
      brandEyebrow: "Phase 1 preview",
      brandTitle: "World Building App",
      brandNote: "Temporary hosted UX surface",
      nav: {
        dashboard: "Dashboard",
        characters: "Characters",
        places: "Places",
        search: "Search",
      },
      previewModeTitle: "Preview mode",
      previewModeDescription: "Static client-side layer for checking UX without live Next.js or PostgreSQL.",
    },
    dashboard: {
      eyebrow: "Active MVP slice",
      title: "Current working-slice dashboard",
      description: "One temporary Pages surface for reviewing structure, cards, forms, tags, links, and search.",
      previewBadges: ["Preview only", "Characters + Places", "Tags, links, search"],
      recentTitle: "Recent preview updates",
      openSearch: "Open search",
      progressTitle: "What can be reviewed now",
      focusTitle: "Current focus",
      focusBadge: "MVP",
      focusDescription: "The preview shows only the active Phase 1 slice with no Story, Map, or postponed sections.",
      reviewCharactersFlow: "Review Characters flow",
      reviewPlacesFlow: "Review Places flow",
      coverageTitle: "Temporary layer coverage",
      coverageBadge: "Mock only",
      coverageDescription: "Create, edit, delete, tags, simple Character↔Place links, and global search all run on client-side mock data only.",
      checklist: [
        "Dashboard reflects only the active MVP entities.",
        "Characters include list, detail, form, tags, and links.",
        "Places mirror the same basic workflow.",
        "Search sees names, slugs, and short descriptions.",
        "Navigation avoids inactive sections.",
      ],
      capabilities: [
        "Dashboard with metrics and recent updates",
        "Characters: mock list/detail/create/edit/delete",
        "Places: mock list/detail/create/edit/delete",
        "Tags: attach/remove",
        "Links: Character ↔ Place add/remove",
        "Search: results across active entities",
      ],
      stats: {
        characters: { eyebrow: "Entities", title: "Characters", suffix: "records in preview" },
        places: { eyebrow: "Entities", title: "Places", suffix: "records in preview" },
        tags: { eyebrow: "Connectivity", title: "Tags", suffix: "available to attach" },
        links: { eyebrow: "Connectivity", title: "Character ↔ Place", suffix: "active links" },
      },
    },
    common: {
      noSelection: "No selection",
      selectFromList: "Select a record from the list.",
      noMatches: "No matching records in preview state.",
      noSummary: "No summary provided",
      noValue: "—",
      selectedPrefix: "Selected:",
      requiredSuffix: "is required.",
      itemsSuffix: "items",
      quickFilter: "Quick filter",
      tagsTitle: "Tags",
      linksTitle: "Linked entities",
      attachTag: "Attach tag",
      removeTag: "Remove",
      addLink: "Create link",
      removeLink: "Delete link",
      linkLabel: "Link label",
      linkPlaceholder: "For example: lives in",
      savedState: "Saved in preview state.",
      selectRecordFirst: "Select a record first.",
      tagAlreadyAttached: "This tag is already attached.",
      linkAlreadyExists: "This link already exists.",
      searchOpenEntity: "Open record",
      searchNoQuery: "Enter a query to see results.",
      searchNoResults: "Nothing matched this query.",
      searchResultsPrefix: "Results for:",
      deleteConfirm: "Delete this record from preview?",
      localeLabel: "Language",
    },
    characters: {
      eyebrow: "MVP entity",
      title: "Characters",
      description: "Temporary working surface for character list, detail, form, tags, and links.",
      newButton: "New Character",
      editButton: "Edit Selected",
      recordsTitle: "List",
      detailTitle: "Character detail",
      deleteButton: "Delete Character",
      form: {
        createTitle: "Create Character",
        editTitle: "Edit Character",
        createMode: "Mode: create",
        editMode: "Mode: edit",
        name: "Name",
        slug: "Slug (optional)",
        summary: "Summary",
        pronouns: "Pronouns",
        epithet: "Epithet",
        status: "Status",
        canon: "Canon",
        save: "Save Character",
        reset: "Reset form",
        searchPlaceholder: "Search by name, slug, or summary",
        statusOptions: { draft: "Draft", active: "Active", archived: "Archived" },
        canonOptions: {
          canonical: "Canonical",
          alternate: "Alternate",
          uncertain: "Uncertain",
          noncanonical: "Noncanonical",
        },
      },
      detailLabels: {
        name: "Name",
        slug: "Slug",
        summary: "Summary",
        profile: "Profile",
        state: "State",
        pronouns: "Pronouns",
        epithet: "Epithet",
      },
      links: {
        targetLabel: "Link to place",
      },
      messages: {
        createDraft: "Preparing a new character draft.",
        selectBeforeEdit: "Select a character before editing.",
        resetToCreate: "Form reset. Ready to create a new record.",
        nothingSelectedToDelete: "Nothing selected to delete.",
        created: "Character created in preview.",
        updated: "Character updated in preview.",
        removed: "Character removed from preview.",
        selectBeforeSave: "Select a record before saving edits.",
      },
    },
    places: {
      eyebrow: "MVP entity",
      title: "Places",
      description: "Temporary working surface for place list, detail, form, tags, and links.",
      newButton: "New Place",
      editButton: "Edit Selected",
      recordsTitle: "List",
      detailTitle: "Place detail",
      deleteButton: "Delete Place",
      form: {
        createTitle: "Create Place",
        editTitle: "Edit Place",
        createMode: "Mode: create",
        editMode: "Mode: edit",
        name: "Name",
        slug: "Slug (optional)",
        summary: "Summary",
        placeKind: "Place kind",
        locationText: "Location note",
        status: "Status",
        canon: "Canon",
        save: "Save Place",
        reset: "Reset form",
        searchPlaceholder: "Search by name, slug, or summary",
        statusOptions: { draft: "Draft", active: "Active", archived: "Archived" },
        canonOptions: {
          canonical: "Canonical",
          alternate: "Alternate",
          uncertain: "Uncertain",
          noncanonical: "Noncanonical",
        },
      },
      detailLabels: {
        name: "Name",
        slug: "Slug",
        summary: "Summary",
        profile: "Location profile",
        state: "State",
        placeKind: "Kind",
        locationText: "Location",
      },
      links: {
        targetLabel: "Link to character",
      },
      messages: {
        createDraft: "Preparing a new place draft.",
        selectBeforeEdit: "Select a place before editing.",
        resetToCreate: "Form reset. Ready to create a new record.",
        nothingSelectedToDelete: "Nothing selected to delete.",
        created: "Place created in preview.",
        updated: "Place updated in preview.",
        removed: "Place removed from preview.",
        selectBeforeSave: "Select a record before saving edits.",
      },
    },
    tags: {
      names: {
        capital: "Capital",
        faction: "Faction",
        witness: "Witness",
        travel: "Travel",
        archive: "Archive",
        frontier: "Frontier",
      },
    },
    search: {
      eyebrow: "Global search",
      title: "Search across the active MVP slice",
      description: "Simple client-side search across Characters and Places only, to review the shared entry point.",
      quickLabel: "Quick search",
      placeholder: "Enter a name, slug, or short description",
      submit: "Search",
      resultsTitle: "Results",
      coverageTitle: "Current coverage",
      coverage: [
        "Characters: name, slug, summary, epithet",
        "Places: name, slug, summary, place kind, location text",
        "Only the active MVP slice, with no Story, Map, or broader entities",
      ],
    },
    entityKinds: {
      character: "Character",
      place: "Place",
    },
  },
};

function resolvePreviewText(path) {
  return String(path ?? "")
    .split(".")
    .reduce((current, segment) => (current == null ? undefined : current[segment]), previewUiText);
}

function getPreviewUiText(locale = "ru") {
  return previewUiText[locale] ?? previewUiText.ru;
}

window.previewUiText = previewUiText;
window.getPreviewUiText = getPreviewUiText;
window.resolvePreviewText = resolvePreviewText;
